name: hcase_ux_examples
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - dash=2.14.2
  - flask=2.2.5
  - ipykernel=6.29.2
  - jupyterlab=4.1.1
  - jupyterlab_server=2.25.3
  - matplotlib-base=3.5.3
  - notebook=7.1.0
  - numpy=1.26.4
  - pandas=1.5.3
  - pip=23.3.1
  - plotly=5.9.0
  - python=3.10.13
  - rdkit=2022.03.5
  - pip:
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - -e ../hcase
