name: hcase_examples
channels:
  - conda-forge
  - defaults
dependencies:
  - hilbertcurve=2.0.5
  - matplotlib=3.8.4
  - networkx=3.3
  - notebook=7.0.8
  - numpy=1.26.4
  - pandas=2.2.2
  - pip=24.2
  - python=3.11.8
  - rdkit=2024.03.5
  - scipy=1.13.1
  - seaborn=0.13.2
  - tqdm=4.66.5
  - pip:
      - scikit-learn==1.5.1
      - jupyter-contrib-nbextensions==0.7.0
      - -e ../
